### PR TITLE
Implement stripping of `s` and `t` parameters from Twitter links.

### PR DESCRIPTION
**Pull request by demize**
Should address #37, though I didn't make it configurable as suggested there.

Also added a test URL to `test_urls.md` and `test_urls.html`.

Did not bump the version in the manifest; I can do that if necessary, though I figured I'd leave it up to the maintainers to decide when to bump the version.

### CODE REVIEW

**Comment by apiraino** [comment]
@demize looks great, thanks!

Minor nit: next time please split code formatting changes in a separate commit, it makes reviewing the actual code changes a little bit easier.

**Comment by apiraino** [comment]
closes #40

**Comment by apiraino** [comment]
closes #37

**Comment by ZacharyTalis** [comment]
Does this PR implement cleaning for `Copy link to Tweet` events? If so, I'm not able to replicate. Cleaning Twitter URLs in the address bar works as expected o7

Specs: Firefox Nightly v104 on Linux w/ `web-ext-run.sh` environment

**Comment by demize** [comment]
> Does this PR implement cleaning for `Copy link to Tweet` events? If so, I'm not able to replicate. Cleaning Twitter URLs in the address bar works as expected o7
> 
> Specs: Firefox Nightly v104 on Linux w/ `web-ext-run.sh` environment

That's my bad; it looks like the cleaners need to be specified separately when the menu item is handled, and I missed that in my initial review. I can create a new PR to fix that tonight.

**Comment by ZacharyTalis** [comment]
thank youuu <3

**Pull request merged**
